import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms — InspoMe",
  description: "Plain-language terms for using InspoMe.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-2xl flex-1 px-5 py-12">
      <Link href="/" className="inline-flex items-center gap-2 font-semibold tracking-tight">
        <span className="inline-block size-6 rounded-md bg-brand" />
        InspoMe
      </Link>

      <h1 className="mt-8 text-3xl font-semibold tracking-tight">Terms of use</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: July 2026</p>

      <div className="mt-8 flex flex-col gap-8 text-sm leading-relaxed">
        <section>
          <h2 className="text-base font-semibold">The short version</h2>
          <p className="mt-2 text-muted-foreground">
            These are plain-language terms for an early product. We&apos;ll
            expand them before general availability. If anything here is
            unclear, email us and we&apos;ll explain.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">What InspoMe does</h2>
          <p className="mt-2 text-muted-foreground">
            InspoMe lets you save links to TikTok and Instagram videos and
            generates an AI analysis of why each video works — hook, structure,
            visuals, editing, and a reusable pattern. It&apos;s a study tool
            for your own content practice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">Your responsibilities</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-muted-foreground">
            <li>Only save content you have the right to view on its original platform.</li>
            <li>Use the analysis for learning and creating your own work, not for copying others&apos; content outright.</li>
            <li>Keep your account credentials to yourself.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold">AI-generated analysis</h2>
          <p className="mt-2 text-muted-foreground">
            Analyses are generated by AI and can be wrong, incomplete, or
            miss context. Treat them as a starting point for your own judgment,
            not a guarantee of performance.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">Availability</h2>
          <p className="mt-2 text-muted-foreground">
            InspoMe is in active development. Features may change, break, or be
            removed while we build. We&apos;ll do our best to keep your saved
            library intact, but you shouldn&apos;t rely on InspoMe as the only
            copy of anything important.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">Contact</h2>
          <p className="mt-2 text-muted-foreground">
            Questions about these terms:{" "}
            <a href="mailto:vinayr787@gmail.com" className="text-foreground underline underline-offset-4">
              vinayr787@gmail.com
            </a>
          </p>
        </section>
      </div>

      <nav className="mt-12 flex items-center gap-5 border-t border-border pt-6 text-sm text-muted-foreground">
        <Link href="/" className="hover:text-foreground">Home</Link>
        <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
        <Link href="/login" className="hover:text-foreground">Sign in</Link>
      </nav>
    </main>
  );
}
